export type Property = {
  id: string
  title: string
  type: 'departamento' | 'casa' | 'ph' | 'local' | 'terreno' | 'loft'
  operation: 'venta' | 'alquiler'
  price: number
  currency: 'USD' | 'ARS'
  address: string
  neighborhood: string
  city: string
  rooms: number | null
  bathrooms: number | null
  covered_area: number | null
  total_area: number | null
  description: string
  features: string[]
  images: string[]
  lat: number
  lng: number
  is_featured: boolean
  status: 'available' | 'reserved' | 'sold'
  agent: string
  created_at: string
}

export type Lead = {
  id: string
  name: string
  email: string
  phone: string
  stage: 'new' | 'contacted' | 'interested' | 'visit' | 'proposal' | 'won' | 'lost'
  source: string
  property_interest: string
  budget: string
  notes: string
  agent: string
  created_at: string
  last_contact: string
}

export type TeamMember = {
  id: string
  name: string
  email: string
  role: 'owner' | 'admin' | 'agent' | 'viewer'
  avatar: string
  phone: string
  properties_count: number
  leads_count: number
}

export type Agency = {
  id: string
  name: string
  slug: string
  plan: 'starter' | 'pro' | 'business' | 'enterprise'
  plan_status: 'active' | 'trial' | 'suspended'
  properties_count: number
  leads_count: number
  members_count: number
  mrr: number
  owner_email: string
  created_at: string
  theme: 'editorial' | 'spatial' | 'loft'
  tagline?: string
  address?: string
  phone?: string
  email?: string
  instagram?: string
}

export const PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'Departamento luminoso en Palermo Soho',
    type: 'departamento',
    operation: 'venta',
    price: 185000,
    currency: 'USD',
    address: 'Thames 1834, Piso 4, Dpto B',
    neighborhood: 'Palermo Soho',
    city: 'Buenos Aires',
    rooms: 2,
    bathrooms: 1,
    covered_area: 68,
    total_area: 72,
    description: 'Hermoso departamento de 2 ambientes en pleno Palermo Soho. Piso 4to por escalera, súper luminoso, frente. Cocina americana renovada, baño completo con ducha. Balcón con vista a la plaza. A metros de cafeterías, gastronomía y transporte.',
    features: ['Luminoso', 'Balcón', 'Cocina renovada', 'Frente', 'Buena ubicación'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    lat: -34.5895,
    lng: -58.4322,
    is_featured: true,
    status: 'available',
    agent: 'Federico Ruiz',
    created_at: '2026-05-12',
  },
  {
    id: 'prop-002',
    title: 'PH con terraza en Villa Crespo',
    type: 'ph',
    operation: 'venta',
    price: 245000,
    currency: 'USD',
    address: 'Loyola 456, PH A',
    neighborhood: 'Villa Crespo',
    city: 'Buenos Aires',
    rooms: 3,
    bathrooms: 2,
    covered_area: 110,
    total_area: 145,
    description: 'Espectacular PH de 3 ambientes con terraza de uso exclusivo de 35m². Dos dormitorios en suite, living comedor amplio, cocina separada equipada. Quincho en terraza. Excelente estado general. Edificio con ascensor.',
    features: ['Terraza propia', 'Quincho', '2 dormitorios en suite', 'Cocina equipada', 'Ascensor'],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ],
    lat: -34.5982,
    lng: -58.4445,
    is_featured: true,
    status: 'available',
    agent: 'Carla Méndez',
    created_at: '2026-05-18',
  },
  {
    id: 'prop-003',
    title: 'Casa 5 ambientes en Caballito',
    type: 'casa',
    operation: 'venta',
    price: 340000,
    currency: 'USD',
    address: 'Rojas 987',
    neighborhood: 'Caballito',
    city: 'Buenos Aires',
    rooms: 5,
    bathrooms: 3,
    covered_area: 210,
    total_area: 280,
    description: 'Magnífica casa de 5 ambientes en Caballito. Planta baja: hall de entrada, living, comedor, cocina-comedor con salida al jardín, baño de cortesía. Planta alta: 3 dormitorios, baño completo, toilette. Garage para 2 autos. Jardín con parrilla.',
    features: ['Garage 2 autos', 'Jardín', 'Parrilla', '3 dormitorios', 'Dos plantas'],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    lat: -34.6197,
    lng: -58.4410,
    is_featured: true,
    status: 'available',
    agent: 'Federico Ruiz',
    created_at: '2026-04-30',
  },
  {
    id: 'prop-004',
    title: 'Departamento 1 ambiente en Belgrano',
    type: 'departamento',
    operation: 'alquiler',
    price: 680,
    currency: 'USD',
    address: 'Mendoza 2341, Piso 7, Dpto C',
    neighborhood: 'Belgrano',
    city: 'Buenos Aires',
    rooms: 1,
    bathrooms: 1,
    covered_area: 38,
    total_area: 38,
    description: 'Moderno monoambiente en el corazón de Belgrano. Piso 7to con vista panorámica. Cocina integrada con desayunador, baño renovado. Edificio con portero eléctrico, lavandería. A pasos del shopping Unicenter y transporte.',
    features: ['Vista panorámica', 'Cocina integrada', 'Portero eléctrico', 'Lavandería', 'Luminoso'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    lat: -34.5601,
    lng: -58.4575,
    is_featured: false,
    status: 'available',
    agent: 'Patricia Ortega',
    created_at: '2026-06-01',
  },
  {
    id: 'prop-005',
    title: 'Departamento 2 amb en Recoleta',
    type: 'departamento',
    operation: 'alquiler',
    price: 950,
    currency: 'USD',
    address: 'Ayacucho 1532, Piso 3, Dpto A',
    neighborhood: 'Recoleta',
    city: 'Buenos Aires',
    rooms: 2,
    bathrooms: 1,
    covered_area: 65,
    total_area: 65,
    description: 'Elegante 2 ambientes en Recoleta. Living amplio con comedor integrado, dormitorio en suite, cocina separada equipada. Edificio clásico con ascensor y encargado. A metros del cementerio de Recoleta y avenidas principales.',
    features: ['Edificio clásico', 'Ascensor', 'Encargado', 'Cocina equipada', 'Buena ubicación'],
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    lat: -34.5880,
    lng: -58.3930,
    is_featured: true,
    status: 'available',
    agent: 'Carla Méndez',
    created_at: '2026-05-25',
  },
  {
    id: 'prop-006',
    title: 'Loft industrial en Palermo Hollywood',
    type: 'loft',
    operation: 'venta',
    price: 198000,
    currency: 'USD',
    address: 'Humboldt 2156, Loft 2B',
    neighborhood: 'Palermo Hollywood',
    city: 'Buenos Aires',
    rooms: 2,
    bathrooms: 1,
    covered_area: 82,
    total_area: 82,
    description: 'Espectacular loft de doble altura en el epicentro de Palermo Hollywood. 7 metros de altura, ventanales industriales de piso a techo, mezzanine privado. Cocina americana con isla. Perfecto para vivir o como espacio de trabajo creativo.',
    features: ['Doble altura', 'Ventanales industriales', 'Mezzanine', 'Cocina con isla', 'Único'],
    images: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
    ],
    lat: -34.5845,
    lng: -58.4298,
    is_featured: true,
    status: 'available',
    agent: 'Federico Ruiz',
    created_at: '2026-05-08',
  },
  {
    id: 'prop-007',
    title: 'Local comercial en San Telmo',
    type: 'local',
    operation: 'alquiler',
    price: 1200,
    currency: 'USD',
    address: 'Defensa 847',
    neighborhood: 'San Telmo',
    city: 'Buenos Aires',
    rooms: null,
    bathrooms: 1,
    covered_area: 95,
    total_area: 95,
    description: 'Excelente local comercial en la peatonal de San Telmo, zona de altísimo tráfico turístico. Frente amplio de 5 metros, planta abierta sin columnas, depósito trasero y baño. Ideal para gastronomía, diseño, galería de arte o showroom.',
    features: ['Alta circulación', 'Frente 5m', 'Depósito', 'Sin columnas', 'Zona turística'],
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    lat: -34.6218,
    lng: -58.3742,
    is_featured: false,
    status: 'available',
    agent: 'Patricia Ortega',
    created_at: '2026-05-20',
  },
  {
    id: 'prop-008',
    title: 'PH 4 ambientes en Colegiales',
    type: 'ph',
    operation: 'venta',
    price: 268000,
    currency: 'USD',
    address: 'Olazábal 2789, PH B',
    neighborhood: 'Colegiales',
    city: 'Buenos Aires',
    rooms: 4,
    bathrooms: 2,
    covered_area: 132,
    total_area: 165,
    description: 'Impecable PH de 4 ambientes con terraza de 33m². Tres dormitorios, dos baños completos, living-comedor de 35m², cocina separada con office. Laundry. Excelente orientación N-O. Edificio boutique de 6 unidades, muy bien mantenido.',
    features: ['Terraza 33m²', '3 dormitorios', '2 baños', 'Edificio boutique', 'Orientación N-O'],
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
    ],
    lat: -34.5738,
    lng: -58.4500,
    is_featured: false,
    status: 'reserved',
    agent: 'Carla Méndez',
    created_at: '2026-04-15',
  },
  {
    id: 'prop-009',
    title: 'Depto 3 amb con cochera en Núñez',
    type: 'departamento',
    operation: 'alquiler',
    price: 1100,
    currency: 'USD',
    address: 'Udaondo 1456, Piso 5, Dpto A',
    neighborhood: 'Núñez',
    city: 'Buenos Aires',
    rooms: 3,
    bathrooms: 2,
    covered_area: 95,
    total_area: 100,
    description: 'Amplio 3 ambientes en Núñez cerca del Estadio Monumental. Dormitorio principal en suite, segundo dormitorio, baño social. Living comedor con balcón corrido. Cocina equipada con lavarropas. Cochera fija incluida en el precio.',
    features: ['Cochera incluida', 'Balcón corrido', '2 baños', 'Cocina equipada', 'Lavarropas'],
    images: [
      'https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800',
      'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?w=800',
    ],
    lat: -34.5458,
    lng: -58.4629,
    is_featured: false,
    status: 'available',
    agent: 'Federico Ruiz',
    created_at: '2026-06-02',
  },
  {
    id: 'prop-010',
    title: 'Terreno en Tigre con acceso al río',
    type: 'terreno',
    operation: 'venta',
    price: 92000,
    currency: 'USD',
    address: 'Arroyo Las Cañas, Canal 2',
    neighborhood: 'Tigre',
    city: 'Tigre, GBA',
    rooms: null,
    bathrooms: null,
    covered_area: null,
    total_area: 800,
    description: 'Terreno de 800m² en el Delta del Tigre con acceso directo al río. Lote con 20 metros de frente al canal. Ideal para construcción de casa de fin de semana o emprendimiento turístico. Cuenta con servicios en el terreno.',
    features: ['Frente al río', '20m de frente', '800m²', 'Servicios', 'Delta Tigre'],
    images: [
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    ],
    lat: -34.4264,
    lng: -58.5786,
    is_featured: false,
    status: 'available',
    agent: 'Patricia Ortega',
    created_at: '2026-05-05',
  },
  {
    id: 'prop-011',
    title: 'Departamento 2 amb en Flores',
    type: 'departamento',
    operation: 'alquiler',
    price: 580,
    currency: 'USD',
    address: 'Av. Rivadavia 6234, Piso 2, Dpto F',
    neighborhood: 'Flores',
    city: 'Buenos Aires',
    rooms: 2,
    bathrooms: 1,
    covered_area: 55,
    total_area: 55,
    description: 'Cómodo 2 ambientes sobre Av. Rivadavia, a pasos del subte y transporte. Dormitorio amplio, living con balcón, cocina separada. Edificio con ascensor. Ideal para parejas o profesionales.',
    features: ['Sobre Rivadavia', 'Balcón', 'Subte a pasos', 'Ascensor', 'Bien comunicado'],
    images: [
      'https://images.unsplash.com/photo-1489171078254-c3365d6e359f?w=800',
      'https://images.unsplash.com/photo-1571508601891-ca5e7a713859?w=800',
    ],
    lat: -34.6282,
    lng: -58.4621,
    is_featured: false,
    status: 'available',
    agent: 'Patricia Ortega',
    created_at: '2026-06-03',
  },
  {
    id: 'prop-012',
    title: 'Local en Once con salón de ventas',
    type: 'local',
    operation: 'alquiler',
    price: 900,
    currency: 'USD',
    address: 'Av. Corrientes 3456',
    neighborhood: 'Once',
    city: 'Buenos Aires',
    rooms: null,
    bathrooms: 1,
    covered_area: 120,
    total_area: 120,
    description: 'Estratégico local comercial en zona de Once sobre Av. Corrientes. Gran salón de ventas de 120m², vitrina de 6 metros, depósito independiente, oficina privada y baño. Ideal para indumentaria, electrónica o mayorista.',
    features: ['Vitrina 6m', 'Depósito', 'Oficina privada', 'Zona comercial', 'Alta circulación'],
    images: [
      'https://images.unsplash.com/photo-1604754742629-3e5728249d73?w=800',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
    ],
    lat: -34.6086,
    lng: -58.4107,
    is_featured: false,
    status: 'available',
    agent: 'Federico Ruiz',
    created_at: '2026-05-28',
  },
]

export const LEADS: Lead[] = [
  {
    id: 'lead-001',
    name: 'María García',
    email: 'maria.garcia@gmail.com',
    phone: '+54 11 4523-8901',
    stage: 'new',
    source: 'Portal Zonaprop',
    property_interest: 'Departamento 2 amb en Recoleta',
    budget: 'USD 800-1100/mes',
    notes: 'Interesada en alquiler. Necesita mudarse en julio. Trabaja en el centro.',
    agent: 'Carla Méndez',
    created_at: '2026-06-05',
    last_contact: '2026-06-05',
  },
  {
    id: 'lead-002',
    name: 'Carlos Rodríguez',
    email: 'carlos.rod@hotmail.com',
    phone: '+54 11 6712-3456',
    stage: 'contacted',
    source: 'Mercado Libre',
    property_interest: 'PH con terraza en Villa Crespo',
    budget: 'USD 220.000-260.000',
    notes: 'Comprador serio. Tiene pre-aprobación hipotecaria. Pidió segunda visita.',
    agent: 'Federico Ruiz',
    created_at: '2026-05-28',
    last_contact: '2026-06-04',
  },
  {
    id: 'lead-003',
    name: 'Ana Martínez',
    email: 'ana.martinez@yahoo.com.ar',
    phone: '+54 11 5634-7890',
    stage: 'interested',
    source: 'Instagram',
    property_interest: 'Departamento 1 amb en Belgrano',
    budget: 'USD 600-750/mes',
    notes: 'Le gustó mucho el departamento. Quiere verlo esta semana. Está decidida.',
    agent: 'Patricia Ortega',
    created_at: '2026-05-30',
    last_contact: '2026-06-03',
  },
  {
    id: 'lead-004',
    name: 'Pedro López',
    email: 'pedro.lopez@empresa.com',
    phone: '+54 11 4456-2345',
    stage: 'visit',
    source: 'Referido',
    property_interest: 'Terreno en Tigre',
    budget: 'USD 80.000-100.000',
    notes: 'Empresario gastronómico. Quiere construir lodge boutique. Visita programada para el sábado.',
    agent: 'Federico Ruiz',
    created_at: '2026-05-15',
    last_contact: '2026-06-05',
  },
  {
    id: 'lead-005',
    name: 'Laura Sánchez',
    email: 'laurasanchez@gmail.com',
    phone: '+54 11 3312-8876',
    stage: 'proposal',
    source: 'Portal Argenprop',
    property_interest: 'PH 4 amb en Colegiales',
    budget: 'USD 250.000-280.000',
    notes: 'Contrapropuesta enviada. Ofrecen USD 255.000 contado. Esperando respuesta del propietario.',
    agent: 'Carla Méndez',
    created_at: '2026-04-20',
    last_contact: '2026-06-04',
  },
  {
    id: 'lead-006',
    name: 'Roberto Díaz',
    email: 'rdiaz.inv@gmail.com',
    phone: '+54 11 7823-1234',
    stage: 'won',
    source: 'Sitio web propio',
    property_interest: 'Casa 5 amb en Caballito',
    budget: 'USD 330.000-350.000',
    notes: '¡CERRADO! Firmó boleto de compra. Precio final USD 338.000. Escritura en agosto.',
    agent: 'Federico Ruiz',
    created_at: '2026-03-10',
    last_contact: '2026-05-30',
  },
  {
    id: 'lead-007',
    name: 'Isabella Fernández',
    email: 'isafernandez@outlook.com',
    phone: '+54 11 5589-4567',
    stage: 'lost',
    source: 'Zonaprop',
    property_interest: 'Loft en Palermo Hollywood',
    budget: 'USD 180.000-200.000',
    notes: 'Cerró con otra inmobiliaria. Compró en Chacarita. Mantener en base para futuras.',
    agent: 'Carla Méndez',
    created_at: '2026-04-05',
    last_contact: '2026-05-10',
  },
  {
    id: 'lead-008',
    name: 'Diego Herrera',
    email: 'diego.herrera@icloud.com',
    phone: '+54 11 6234-9012',
    stage: 'new',
    source: 'Facebook Ads',
    property_interest: 'PH 4 amb en Colegiales',
    budget: 'USD 1.000-1.200/mes',
    notes: 'Familia de 4. Necesita 3 dormitorios mínimo. Vienen de Mendoza. Sin mascotas.',
    agent: 'Patricia Ortega',
    created_at: '2026-06-04',
    last_contact: '2026-06-04',
  },
  {
    id: 'lead-009',
    name: 'Valentina Torres',
    email: 'vale.torres@gmail.com',
    phone: '+54 11 4890-5678',
    stage: 'contacted',
    source: 'Mercado Libre',
    property_interest: 'Departamento 2 amb en Recoleta',
    budget: 'USD 850-1.000/mes',
    notes: 'Profesional de salud. Quiere zona tranquila con acceso a hospitales. Le enviamos opciones.',
    agent: 'Carla Méndez',
    created_at: '2026-06-01',
    last_contact: '2026-06-03',
  },
  {
    id: 'lead-010',
    name: 'Matías Flores',
    email: 'mflores.arq@gmail.com',
    phone: '+54 11 3478-2345',
    stage: 'visit',
    source: 'Instagram',
    property_interest: 'PH con terraza en Villa Crespo',
    budget: 'USD 230.000-260.000',
    notes: 'Arquitecto. Le interesa para reformar. Visita técnica el martes con su socio.',
    agent: 'Federico Ruiz',
    created_at: '2026-05-22',
    last_contact: '2026-06-02',
  },
]

export const TEAM: TeamMember[] = [
  {
    id: 'member-001',
    name: 'Martín López',
    email: 'martin.lopez@lopezasociados.com',
    role: 'owner',
    avatar: 'ML',
    phone: '+54 11 4512-3456',
    properties_count: 12,
    leads_count: 10,
  },
  {
    id: 'member-002',
    name: 'Carla Méndez',
    email: 'carla.mendez@lopezasociados.com',
    role: 'admin',
    avatar: 'CM',
    phone: '+54 11 5623-7890',
    properties_count: 5,
    leads_count: 4,
  },
  {
    id: 'member-003',
    name: 'Federico Ruiz',
    email: 'federico.ruiz@lopezasociados.com',
    role: 'agent',
    avatar: 'FR',
    phone: '+54 11 6734-1234',
    properties_count: 4,
    leads_count: 4,
  },
  {
    id: 'member-004',
    name: 'Patricia Ortega',
    email: 'patricia.ortega@lopezasociados.com',
    role: 'agent',
    avatar: 'PO',
    phone: '+54 11 7845-5678',
    properties_count: 3,
    leads_count: 3,
  },
]

export const AGENCIES: Agency[] = [
  {
    id: 'agency-001',
    name: 'López & Asociados',
    slug: 'lopez-asociados',
    plan: 'pro',
    plan_status: 'active',
    properties_count: 12,
    leads_count: 10,
    members_count: 4,
    mrr: 299,
    owner_email: 'martin.lopez@lopezasociados.com',
    created_at: '2026-01-15',
    theme: 'editorial',
    tagline: 'Más de 15 años conectando familias con propiedades en Buenos Aires.',
    address: 'Av. Santa Fe 2034, Piso 2, Palermo — Buenos Aires',
    phone: '+54 11 4512-3456',
    email: 'contacto@lopezasociados.com',
    instagram: '@lopezasociados_ba',
  },
  {
    id: 'agency-002',
    name: 'Remax Capital',
    slug: 'remax-capital',
    plan: 'business',
    plan_status: 'active',
    properties_count: 48,
    leads_count: 67,
    members_count: 12,
    mrr: 599,
    owner_email: 'admin@remaxcapital.com.ar',
    created_at: '2026-02-01',
    theme: 'spatial',
    tagline: 'Encontrá tu próxima propiedad en el mapa.',
    address: 'Reconquista 880, Microcentro — Buenos Aires',
    phone: '+54 11 4000-9000',
    email: 'admin@remaxcapital.com.ar',
    instagram: '@remaxcapital',
  },
  {
    id: 'agency-003',
    name: 'Propiedades del Sur',
    slug: 'propiedades-del-sur',
    plan: 'starter',
    plan_status: 'trial',
    properties_count: 6,
    leads_count: 8,
    members_count: 2,
    mrr: 0,
    owner_email: 'contacto@propiedadesdelsur.com',
    created_at: '2026-05-20',
    theme: 'editorial',
    tagline: 'Propiedades únicas en el sur de Buenos Aires.',
    address: 'Av. Rivadavia 5000, Caballito',
    phone: '+54 11 4904-1234',
    email: 'contacto@propiedadesdelsur.com',
  },
  {
    id: 'agency-004',
    name: 'Inversiones Norte',
    slug: 'inversiones-norte',
    plan: 'pro',
    plan_status: 'active',
    properties_count: 23,
    leads_count: 31,
    members_count: 6,
    mrr: 299,
    owner_email: 'info@inversionesnorte.com.ar',
    created_at: '2026-03-10',
    theme: 'spatial',
    tagline: 'Invertí en propiedades con respaldo profesional.',
    address: 'Libertador 7500, Núñez',
    phone: '+54 11 5234-0000',
    email: 'info@inversionesnorte.com.ar',
  },
  {
    id: 'agency-005',
    name: 'Palermo Homes',
    slug: 'palermo-homes',
    plan: 'business',
    plan_status: 'suspended',
    properties_count: 18,
    leads_count: 22,
    members_count: 5,
    mrr: 0,
    owner_email: 'owner@palermohomes.com.ar',
    created_at: '2026-02-28',
    theme: 'loft',
    tagline: 'Propiedades de lujo en los barrios más exclusivos.',
    address: 'Thames 1850, Palermo Soho',
    phone: '+54 11 4833-7000',
    email: 'owner@palermohomes.com.ar',
    instagram: '@palermohomes',
  },
]

export const AGENCY_STATS = {
  total_properties: 12,
  available_properties: 9,
  featured_properties: 5,
  total_leads: 10,
  new_leads: 2,
  leads_this_month: 6,
  visits_this_month: 234,
  contacts_this_month: 18,
  conversion_rate: 8.5,
  monthly_views: [180, 210, 195, 245, 289, 234],
  leads_by_stage: {
    new: 2,
    contacted: 2,
    interested: 1,
    visit: 2,
    proposal: 1,
    won: 1,
    lost: 1,
  },
}

export const PLATFORM_STATS = {
  total_agencies: 5,
  active_agencies: 3,
  trial_agencies: 1,
  total_properties: 107,
  total_leads: 138,
  mrr: 1196,
  arr: 14352,
  monthly_growth: 23,
}
